### ISSUE TITLE
Чел..

### ISSUE THREAD

**Issue by LepinVlados** [cummarik/cummarik.github.io#1]
А ты хорош

**Comment by cummarik** [comment]
> А ты хорош

Согл

**Comment by LepinVlados** [comment]
Даня ты почему ещё не в ****колледже?****

**Comment by LepinVlados** [comment]
______Какой ты долгий_____

**Comment by cummarik** [comment]
> Даня ты почему ещё не в ****колледже?****

я то был как раз таки
